name: CI
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.17"
      - run: npm ci --no-optional
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Create assets
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          zip -qr build.zip ./build
          zip -qr coverage.zip ./coverage
      - name: Create a release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain bright-twig.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      - name: Upload Coverage Reports
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
