name: Shell Commands
on:
  - push
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    environment: DEBUG
    steps:
      - name: echo a string
        run: echo a string
      - name: multiline script
        run: |
          node -v
          npm -v